#!/bin/bash
##!/bin/bash

set -e

HOST_CC=${CC:-gcc}

cd src
$HOST_CC build.c -D__CATALINA__ -o build
./build
cd ..

if [[ "$1" != "" ]]; then

   # also build cake for the specified Propeller platform
   make_cake $@

fi
