#!/bin/bash
set -e

cp catopt_0 $LCCDIR/bin
cp catopt_1 $LCCDIR/bin
cp catopt_2 $LCCDIR/bin
cp catopt_3 $LCCDIR/bin
cp catopt_4 $LCCDIR/bin
cp catopt_5 $LCCDIR/bin
cp catopt_6 $LCCDIR/bin
cp catopt_7 $LCCDIR/bin
cp catopt_8 $LCCDIR/bin
cp catopt_9 $LCCDIR/bin
cp catopt_10 $LCCDIR/bin
cp catopt_11 $LCCDIR/bin
cp catopt_12 $LCCDIR/bin
cp catopt_13 $LCCDIR/bin
cp catoptimize $LCCDIR/bin
cp cmmopt_0 $LCCDIR/bin
cp cmmopt_1 $LCCDIR/bin
cp cmmopt_2 $LCCDIR/bin
cp cmmopt_3 $LCCDIR/bin
cp cmmopt_4 $LCCDIR/bin
cp cmmopt_5 $LCCDIR/bin
cp cmmopt_6 $LCCDIR/bin
cp cmmopt_7 $LCCDIR/bin
cp cmmopt_8 $LCCDIR/bin
cp cmmopt_9 $LCCDIR/bin
cp cmmopt_10 $LCCDIR/bin
cp cmmopt_11 $LCCDIR/bin
cp cmmopt_12 $LCCDIR/bin
cp cmmopt_13 $LCCDIR/bin
cp cmmopt_13 $LCCDIR/bin
cp cmmopt_14 $LCCDIR/bin
cp cmmoptimize $LCCDIR/bin
