#!/bin/bash
##!/bin/bash -login
#
# build all the components of Catalina in the correct sequence. Note that
# this script assumes all the necessary tools (gcc, bison, flex etc) are
# already installed
#
set -e

HOST_OS=$(uname -s)
if [[ "$HOST_OS" == "Darwin" ]] ; then
   for TOOL_PATH in \
      /opt/homebrew/opt/bison/bin \
      /opt/homebrew/opt/flex/bin \
      /usr/local/opt/bison/bin \
      /usr/local/opt/flex/bin
   do
      if [[ -d "$TOOL_PATH" ]] ; then
         PATH="$TOOL_PATH:$PATH"
      fi
   done
   export PATH
fi

TMP_LCCDIR=$LCCDIR
if [[ "$TMP_LCCDIR" == "" ]] ; then
   if [[ "$HOST_OS" == "Darwin" ]] ; then
      TMP_LCCDIR=$(cd .. && pwd)
   else
      TMP_LCCDIR=/opt/catalina
   fi
fi
export LCCDIR=$TMP_LCCDIR
#
if [[ ! -e "$TMP_LCCDIR/bin/catalina_env" ]] ; then
   clear
   echo ""
   echo "ERROR: Catalina does not appear to be installed in $TMP_LCCDIR"
   echo "";
   echo "Set the environment variable LCCDIR to where Catalina is installed.";
   echo "";
   exit
fi
#
source ../use_catalina
#
cd catalina
./build_all
cd ../cake
./build_all
./copy_all
cd ../catoptimize
./build_all
./copy_all
cd ../p2asm_src
./build_all
cd ../lcc
./build_all
cd ../openspin
./build_all
cd ..
#
echo "Done!"
#
